# Imports

In [6]:
import numpy as np

### Row Matrix

Row matrix: A matrix having a single row. Example:[1 2 3 4 5].

In [40]:
# Creating row matrix using NumPy
matrix_1 = np.array([1, 2, 3, 4, 5])
matrix_2 =np.array([6,7,8,9,10])

In [9]:
# printing the matrix
print(matrix_1)

[1 2 3 4 5]


In [49]:
# Performing Matrix addition
matrix_3 = np.add(matrix_1,matrix_2)
print(f'{matrix_1} + {matrix_2} = {matrix_3}')

[1 2 3 4 5] + [ 6  7  8  9 10] = [ 7  9 11 13 15]


In [50]:
# Performing Matrix Subtraction
matrix_3 = np.subtract(matrix_2,matrix_1)
print(f'{matrix_2} - {matrix_1} = {matrix_3}')

[ 6  7  8  9 10] - [1 2 3 4 5] = [5 5 5 5 5]


In [68]:
# Performing Matrix multiplication 
matrix_3 = np.matmul(matrix_2,matrix_1)
print(f'{matrix_1} * {matrix_2} = {matrix_3}')

[1 2 3 4 5] * [ 6  7  8  9 10] = 130


In [70]:
# Performing Flattening
matrix_4 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
matrix_4.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [73]:
# Performing Flattening
matrix_4 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
matrix_4.transpose()

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [97]:
# Performing Matrix multiplication 
matrix_1_1 = np.array([[1,2], [6,7]])
matrix_1_2 = np.array([[4,5], [8,9]])
                    
matrix_3 = np.dot(matrix_1_1,matrix_1_2)
print(f'{matrix_3}')

[[20 23]
 [80 93]]


In [91]:
# Performing Matrix multiplication 
matrix_1_1 = np.array([[1,2], [6,7]])
matrix_1_2 = np.array([[4,5], [8,9]])
                    
matrix_3 = np.matmul(matrix_1_1,matrix_1_2)
print(f'{matrix_3}')

[[20 23]
 [80 93]]


In [93]:
# Performing Matrix multiplication 
matrix_1_1 = np.array([[1,2], [6,7]])
matrix_1_2 = np.array([[4,5], [8,9]])
                    
matrix_3 = np.multiply(matrix_1_1,matrix_1_2)
print(f'{matrix_3}')

[[ 4 10]
 [48 63]]


In [109]:
matrix_1_1 = np.array([[1,2,3], [6,7,8]])
matrix_1_2 = np.array([[4,5], [8,9],[10,11]])

matrix_1_3 = np.array([[1,2], [6,7]])
matrix_1_4 = np.array([[4,5], [8,9]])

print(f'Dot =\n {np.dot(matrix_1_1,matrix_1_2)}')
print(f'multiply =\n {np.multiply(matrix_1_3,matrix_1_4)}')
print(f'Matmul =\n {np.matmul(matrix_1_1,matrix_1_2)}') 

Dot =
 [[ 50  56]
 [160 181]]
multiply =
 [[ 4 10]
 [48 63]]
Matmul =
 [[ 50  56]
 [160 181]]
