# Imports

In [1]:
import numpy as np

# Types of Matrix :-

- ### Row Matrix

  **Row matrix**: A matrix having a single row. Example:[1 2 3 4 5].

In [2]:
# Creating row matrix using NumPy
matrix_row = np.array([1, 2, 3, 4, 5])

# printing the matrix
print(matrix_row)

[1 2 3 4 5]


In [3]:
# printing the matrix
print(f'Row matrix = {matrix_row}')

Row matrix = [1 2 3 4 5]


- ### Column Matrix
  A matrix that consists of all elements in only one column is called a **column matrix**.EX:-    
              |1|
      Matrix= |2|
              |3|

In [4]:
# Creating column matrix using NumPy
matrix_column = np.array([[1],[2],[3],[4],[5]])

# printing the matrix
print(f'Column matrix =\n{matrix_column}')

Column matrix =
[[1]
 [2]
 [3]
 [4]
 [5]]


- ### Zero Matrix
  A **zero matrix or null matrix** is a matrix all of whose entries are zero. EX:-    
                   |0 0 0|
      Zero Matrix= |0 0 0|
                   |0 0 0|

In [13]:
# Creating zero matrix using NumPy
matrix_zero = np.array([[0, 0, 0],[0, 0, 0],[0, 0, 0]])

# printing the matrix
print(f'Zero matrix =\n{matrix_zero}')

Zero matrix =
[[0 0 0]
 [0 0 0]
 [0 0 0]]


- ### Singleton Matrix
  If in a matrix there is only one element then it is called **singleton matrix**. EX:-    
  
                singleton matrix = [2]

In [14]:
# Creating singleton matrix using NumPy
matrix_singleton = np.array([2])

# printing the matrix
print(f'Singleton matrix =\n{matrix_singleton}')

Singleton matrix =
[2]


- ### Horizontal Matrix
  
  A matrix, in which number of rows is less than the number of columns, is called a **Horizontal Matrix**.
  
              Horizontal matrix= [[ 1  2  3  4 ]  
                                 [ 5  6  7  8 ]]  

In [3]:
# Creating horizontal matrix using NumPy
matrix_horizontal = np.array([[1,2,3,4],[5,6,7,8]])

# printing the matrix
print(f'Horizontal matrix=\n{matrix_horizontal}\n')

Horizontal matrix=
[[1 2 3 4]
 [5 6 7 8]]



- ### Vertical Matrix
  
  A matrix, in which number of columns is less than the number of rows, is called a **Vertical Matrix**.
  
               Vertical matrix= [[ 1  2]  
                                 [ 3  4]
                                 [ 5  6]]  

In [5]:
# Creating vertical matrix using NumPy
matrix_vertical = np.array([[1,2],[3,4],[5,6]])

# printing the matrix
print(f'Vertical matrix=\n{matrix_vertical}\n')

Vertical matrix=
[[1 2]
 [3 4]
 [5 6]]



- ### Square Matrix

  A square matrix is an n × n matrix; that is, a matrix having the same number of rows as columns. EX:-      
     
                                [[1 2 3]  
               Square Matrix=    [4 5 6]  
                                 [7 8 9]]

In [24]:
# Creating square matrix using NumPy
matrix_square = np.array([[1,2],[3,4]])

# printing the matrix
print(f'Square matrix=\n{matrix_square}')

Square matrix=
[[1 2]
 [3 4]]


- ### Upper Triangular Matrix
  
  A square matrix is called **upper triangular** if all the entries below the main diagonal are zero
  
                                                   [[ 1  2  3  4 ]  
                         Upper triangular matrix=   [ 0  5  6  7 ]  
                                                    [ 0  0  8  9 ]  
                                                    [ 0  0  0  10]]  

In [50]:
# Creating upper triangular matrix using NumPy
matrix_upper_triangular = np.array([[1,2,3,4],[0,5,6,7],[0,0,8,9],[0,0,0,10]])

# printing the matrix
print(f'Upper triangular matrix=\n{matrix_upper_triangular}\n')

Upper triangular matrix=
[[ 1  2  3  4]
 [ 0  5  6  7]
 [ 0  0  8  9]
 [ 0  0  0 10]]



- ### Lower Triangular Matrix
  
  A square matrix is called **lower triangular** if all the entries above the main diagonal are zero
  
                                                   [[ 1  0  0  0 ]  
                         lower triangular matrix=   [ 2  3  0  0 ]  
                                                    [ 4  5  6  0 ]  
                                                    [ 7  8  9  10]]  

In [47]:
# Creating lower triangular matrix using NumPy
matrix_lower_triangular = np.array([[1,0,0,0],[2,3,0,0],[4,5,6,0],[7,8,9,10]])

# printing the matrix
print(f'Lower triangular matrix=\n{matrix_lower_triangular}\n')

Lower triangular matrix=
[[ 1  0  0  0]
 [ 2  3  0  0]
 [ 4  5  6  0]
 [ 7  8  9 10]]



- ### Symmetric Matrix

  A matrix A is **symmetric matrix** if it is equal to its transpose, i.e., A=AT. A matrix A is symmetric if and only if swapping indices   doesn't change its components, i.e., aij=aji.  
                                        [[ 1  2  3  4]  
                   Symmetric matrix=    [ 2  5  6  7]  
                                        [ 3  6  8  9]  
                                        [ 4  7  9 10]]  

In [6]:
# Creating symmetric matrix using NumPy
matrix_symmetric = np.array([[1,2,3,4],[2,5,6,7],[3,6,8,9],[4,7,9,10]])

# printing the matrix
print(f'Symmetric matrix=\n{matrix_symmetric}\n')

# Using .transpose() function of NumPY to calculate the matrix's transpose
# printing the transpose of the matrix
print(f'Transpose of the symmetric matrix=\n{matrix_symmetric.transpose()}')

Symmetric matrix=
[[ 1  2  3  4]
 [ 2  5  6  7]
 [ 3  6  8  9]
 [ 4  7  9 10]]

Transpose of the symmetric matrix=
[[ 1  2  3  4]
 [ 2  5  6  7]
 [ 3  6  8  9]
 [ 4  7  9 10]]


- ### Skew-Symmetric Matrix
  
  Square Matrix A is said to be skew-symmetric if aij=−aji for all i and j. In other words, we can say that matrix A is said to    be **skew-symmetric** if transpose of matrix A is equal to negative of Matrix A i.e (AT=−A).  
  
                                                   [[ 0 -1  3  6]  
                         Skew-Symmetric matrix=     [ 1  0  2 -5]  
                                                    [-3 -2  0  4]  
                                                    [-6  5 -4  0]]  

In [16]:
# Creating skew-symmetric matrix using NumPy
matrix_skew_symmetric = np.array([[0,-1,3,6],[1,0,2,-5],[-3,-2,0,4],[-6,5,-4,0]])

# printing the matrix
print(f'Skew-Symmetric matrix=\n{matrix_skew_symmetric}\n')

# Using .transpose() function of NumPY to calculate the matrix's transpose
matrix_skew_symmetric_t=matrix_skew_symmetric.transpose()

# printing the transpose of the matrix
print(f'Transpose of the Skew-Symmetric matrix=\n{matrix_skew_symmetric_t}\n')

# printing the negative of transpose matrix
print(f'Negative of the Transpose matrix=\n{matrix_skew_symmetric_t*-1}')

Skew-Symmetric matrix=
[[ 0 -1  3  6]
 [ 1  0  2 -5]
 [-3 -2  0  4]
 [-6  5 -4  0]]

Transpose of the Skew-Symmetric matrix=
[[ 0  1 -3 -6]
 [-1  0 -2  5]
 [ 3  2  0 -4]
 [ 6 -5  4  0]]

Negative of the Transpose matrix=
[[ 0 -1  3  6]
 [ 1  0  2 -5]
 [-3 -2  0  4]
 [-6  5 -4  0]]


- ### Orthogonal Matrix
  
  The matrix is said to be an **orthogonal matrix** if the product of a matrix and its transpose gives an identity value.
  Q^T . Q = Q . Q^T = I
  
                                                   [[ 1  0 ]  
                         Orthogonal matrix=         [ 0 -1 ]]  

In [23]:
# Creating orthogonal matrix using NumPy
matrix_orthogonal = np.array([[1,0],[0,-1]])

# printing the matrix
print(f'Orthogonal matrix=\n{matrix_orthogonal}\n')

# Using .transpose() function of NumPY to calculate the matrix's transpose 
# Printing original matrix * transpose of the matrix, which is equal to an indentity matrix
print(f'Orthogonal matrix * Transpose of orthogonal matrix= Indentity Matrix =\n{matrix_orthogonal.transpose()*matrix_orthogonal}\n')

Orthogonal matrix=
[[ 1  0]
 [ 0 -1]]

Orthogonal matrix * Transpose of orthogonal matrix= Indentity Matrix =
[[1 0]
 [0 1]]



- ### Diagonal Matrix
  
  A **diagonal matrix** is a matrix in which the entries outside the main diagonal are all zero
  
                                                   [[ 1  0  0  0 ]  
                         Diagonal matrix=           [ 0  2  0  0 ]  
                                                    [ 0  0  3  0 ]  
                                                    [ 0  0  0  4]]  

In [52]:
# Creating diagonal matrix using NumPy
matrix_diagonal = np.array([[1,0,0,0],[0,2,0,0],[0,0,3,0],[0,0,0,4]])

# printing the matrix
print(f'Diagonal matrix=\n{matrix_diagonal}\n')

Diagonal matrix=
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]



- ### Identity Matrix
  
  **Identity matrix** of size n is the n × n square matrix with ones on the main diagonal and zeros elsewhere.
  
                                [[1 0 0]  
               Identity Matrix=  [0 1 0]  
                                 [0 0 1]]

In [8]:
# Creating identity matrix using NumPy
matrix_identity = np.array([[1,0,0],[0,1,0],[0,0,1]])

# printing the matrix
print(f'Identity matrix=\n{matrix_identity}\n')

Identity matrix=
[[1 0 0]
 [0 1 0]
 [0 0 1]]



- ### Scalar matrix
  
  A **scalar matrix** is a special kind of diagonal matrix. It is a diagonal matrix with equal-valued elements along the diagonal. 
  
                                [[2 0 0]  
               Scalar Matrix=    [0 2 0]  
                                 [0 0 2]]

In [25]:
# Creating identity matrix using NumPy
matrix_scalar = np.array([[2,0,0],[0,2,0],[0,0,2]])

# printing the matrix
print(f'Scalar matrix=\n{matrix_scalar}\n')

Scalar matrix=
[[2 0 0]
 [0 2 0]
 [0 0 2]]



- ### Hermitian Matrix

  **Hermitian Matrix** (or self-adjoint matrix) is a complex square matrix that is equal to its own conjugate transpose—that is, the element in the i-th row and j-th column is equal to the complex conjugate of the element in the j-th row and i-th column    

In [120]:
# Creating hermitian matrix using NumPy
# Python has Built-in Support for Complex Numbers, complex([real[, imag]]). where the Imaginary Part is Written with a j Suffix, e.g., 3+1j. 

matrix_hermitian = np.array([[-1 , 1-2j , 0], [1+2j , 0 , -1j ], [0, 1j, 1]])

# printing the matrix
print(f'Hermitian Matrix=\n{matrix_hermitian}\n')

# Printing the transpose of the conjugate matrix using .conjugate() and .transpose() NumPy function
print(f'Transpose of conjugate Matrix=\n{matrix_hermitian.conjugate().transpose()}')

Hermitian Matrix=
[[-1.+0.j  1.-2.j  0.+0.j]
 [ 1.+2.j  0.+0.j -0.-1.j]
 [ 0.+0.j  0.+1.j  1.+0.j]]

Transpose of conjugate Matrix=
[[-1.-0.j  1.-2.j  0.-0.j]
 [ 1.+2.j  0.-0.j  0.-1.j]
 [ 0.-0.j -0.+1.j  1.-0.j]]


- ### Singular Matrix

   **Singular Matrix** is a square matrix that does not have a matrix inverse. A matrix is singular if its determinant is 0.

In [129]:
# Creating singular matrix using NumPy
matrix_singular = np.array([[1,2],[1,2]])

# printing the matrix
print(f'Singular matrix=\n{matrix_singular}\n')

# calculating determinant of the matrix using np.linalg.det() function
print(f'Determinant of the matrix = {np.linalg.det(matrix_singular)}')

Singular matrix=
[[1 2]
 [1 2]]

Determinant of the matrix = 0.0


- ### NonSingular Matrix

  A **non-singular matrix** is a square one whose determinant is not zero.

In [131]:
# Creating non-singular matrix using NumPy
matrix_non_singular = np.array([[1,2],[3,2]])

# printing the matrix
print(f'NonSingular matrix=\n{matrix_non_singular}\n')

# calculating determinant of the matrix using np.linalg.det() function
print(f'Determinant of the matrix = {np.linalg.det(matrix_non_singular)}')

NonSingular matrix=
[[1 2]
 [3 2]]

Determinant of the matrix = -4.000000000000001


# Operations of Matrices :-

- ### Addition of Matrices

    If A[aij]mxn and B[bij]mxn are two matrices of the same order then their sum A + B is a matrix, and each element of that 
    matrix is the sum of the corresponding elements. i.e. A + B = [aij + bij]mxn
    
    We can Perform Matrix Addition on All Types of Matrix With Same Order.

In [83]:
# Creating 2 2D matrix using Numpy
matrix_A = np.array([[1, 2, 3], [4, 5, 6]])
matrix_B = np.array([[6, 5, 4], [3, 2, 1]])

# Performing Matrix addition using NumPY's add() function
print(f"Matrix addition using NumPY's add() function:-\n{matrix_A}\n    +\n{matrix_B}\n    =\n{np.add(matrix_A, matrix_B)}\n")

# Performing Matrix addition using simple '+' sign
print(f"Matrix addition using simple '+' sign:-\n{matrix_A}\n    +\n{matrix_B}\n    =\n{matrix_A+ matrix_B}")

Matrix addition using NumPY's add() function:-
[[1 2 3]
 [4 5 6]]
    +
[[6 5 4]
 [3 2 1]]
    =
[[7 7 7]
 [7 7 7]]

Matrix addition using simple '+' sign:-
[[1 2 3]
 [4 5 6]]
    +
[[6 5 4]
 [3 2 1]]
    =
[[7 7 7]
 [7 7 7]]


- ### Subtraction of Matrices

  If A and B are two matrices of the same order, then we define A-B=A+\left( -B \right).A−B=A+(−B).

In [86]:
# Creating 2 2D numpy using Numpy
matrix_A = np.array([[1, 2], [3,4]])
matrix_B = np.array([[5,6], [7,8]])

# Performing Matrix subtraction using NumPY's subtract() function
print(f"Matrix subtraction using NumPY's subtract() function:-\n{matrix_B}\n   -\n{matrix_A}\n   =\n{np.subtract(matrix_B, matrix_A)}\n")

# Performing Matrix addition using simple '-' sign
print(f"Matrix subtraction using simple '-' sign:-\n{matrix_B}\n   -\n{matrix_A}\n   =\n{matrix_B- matrix_A}")

Matrix subtraction using NumPY's subtract() function:-
[[5 6]
 [7 8]]
   -
[[1 2]
 [3 4]]
   =
[[4 4]
 [4 4]]

Matrix subtraction using simple '-' sign:-
[[5 6]
 [7 8]]
   -
[[1 2]
 [3 4]]
   =
[[4 4]
 [4 4]]


- ### Scalar Multiplication of Matrices

  The term scalar multiplication refers to the product of a real number and a matrix. In scalar multiplication, each entry in the matrix is multiplied by the given scalar.

In [101]:
# Creating a 2D matrix using Numpy
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

# Performing Matrix scalar multiplication using NumPY's multiply() function
print(f"Matrix scalar multiplication using NumPY's multiply() function:-\n{matrix}\n    *\n    5\n    =\n{np.multiply(matrix,5)}\n")

# Performing Matrix scalar multiplication using simple '*' sign
print(f"Matrix scalar multiplication using simple '*' sign:-\n{matrix}\n    *\n    5\n    =\n{matrix*5}")

Matrix scalar multiplication using NumPY's multiply() function:-
[[1 2 3]
 [4 5 6]
 [7 8 9]]
    *
    5
    =
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]

Matrix scalar multiplication using simple '*' sign:-
[[1 2 3]
 [4 5 6]
 [7 8 9]]
    *
    5
    =
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


- ### Multiplication of Matrices

    Let A = [aij]m x n and B = [bij]n x p Are Two Matrices Such That the Number of Columns of A is Equal to the Number of Rows of B, then Multiplication of A and B is Denoted by AB

    We Can Multiply any Two Matrices With The Order Of M x N And N x P And It Will Give Us a M x P Order Matrix

In [149]:
# Creating 2 2D matrix using Numpy
matrix_A = np.array([[1, 2], [3,4]])
matrix_B = np.array([[5,6], [7,8]])

# Performing Matrix multiplication using NumPY's matmul() function
print(f"Matrix scalar multiplication using NumPY's matmul() function:-\n{matrix_A}\n   *\n{matrix_B}\n   =\n{np.matmul(matrix_A,matrix_B)}\n")

# Performing Matrix multiplication using NumPY's dot() function
print(f"Matrix scalar multiplication using NumPY's dot() function:-\n{matrix_A}\n   *\n{matrix_B}\n   =\n{np.dot(matrix_A,matrix_B)}\n")

Matrix scalar multiplication using NumPY's matmul() function:-
[[1 2]
 [3 4]]
   *
[[5 6]
 [7 8]]
   =
[[19 22]
 [43 50]]

Matrix scalar multiplication using NumPY's dot() function:-
[[1 2]
 [3 4]]
   *
[[5 6]
 [7 8]]
   =
[[19 22]
 [43 50]]



- ### Transpose of Matrix

    Transpose of a matrix is given by interchanging of rows and columns.Matrix Transpose Can be Done in any Types of Matrix of Order M x N, Where Value of M And N is Grater Than 1.

In [119]:
# Creating a 2D matrix using Numpy
matrix = np.array([[1,2,3], [4,5,6],[7,8,9]])

# Calculating Transpose of matrix using NumPY's transpose() function
print(f"Transpose of matrix using NumPY's transpose() function:-\nA=\n{matrix}\nTranspose of A=\n{np.transpose(matrix)}\n")

# Calculating Transpose of matrix using NumPY's .T method
print(f"Transpose of matrix using NumPY's .T function :-\nA=\n{matrix}\nTranspose of A=\n{matrix.T}\n")

Transpose of matrix using NumPY's transpose() function:-
A=
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose of A=
[[1 4 7]
 [2 5 8]
 [3 6 9]]

Transpose of matrix using NumPY's .T function :-
A=
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose of A=
[[1 4 7]
 [2 5 8]
 [3 6 9]]



- ### Determinant of Matrix

    The determinant is a scalar value that can be computed from the elements of a square matrix and encodes certain properties of the linear transformation described by the matrix. The determinant of a matrix A is denoted det(A), det A, or |A|. Geometrically, it can be viewed as the volume scaling factor of the linear transformation described by the matrix. This is also the signed volume of the n-dimensional parallelepiped spanned by the column or row vectors of the matrix. The determinant is positive or negative according to whether the linear transformation preserves or reverses the orientation of a real vector space.

In [134]:
# Creating a 2D matrix using Numpy
matrix = np.array([[1,2,3], [4,5,6],[7,8,9]])

# Calculating Determinant of Matrix using NumPY's np.linalg.det() function
print(f"Determinant of Matrix using NumPY's transpose() function:-\nA=\n{matrix}\n\nDeterminante of A= {np.linalg.det(matrix)}\n")

Determinant of Matrix using NumPY's transpose() function:-
A=
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Determinante of A= -9.51619735392994e-16



- ### Flatten of Matrix

    The process of converting 2D or multi-Dimensional matrix into a 1-D matrix or Array 

In [148]:
# Creating a 2D matrix using Numpy
matrix = np.array([[1,2,3], [4,5,6],[7,8,9]])

# Flattening a Matrix using NumPY's .flatten() function
#parameters of flatten() function are:-
#‘C’ means to flatten in row-major (C-style) order.
#‘F’ means to flatten in column-major (Fortran- style) order.
#‘A’ means to flatten in column-major order if a is Fortran contiguous in memory, row-major order otherwise.
#‘K’ means to flatten a in the order the elements occur in memory. The default is ‘C’.
print(f" Flattening a Matrix using NumPY's .flatten() function:-\nA=\n{matrix}\n\nFlatten of A= {matrix.flatten()}\n")

 Flattening a Matrix using NumPY's .flatten() function:-
A=
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Flatten of A= [1 2 3 4 5 6 7 8 9]



- ### Inverse of Matrix

  Assuming that we have a square matrix A, which is non-singular (i.e. det (A) does not equal zero), then there exists an n × n matrix A-1 which is called the inverse of A such that:
  AA-1 = A-1A = I, where I is the identity matrix.


In [153]:
# Creating a 2D matrix using Numpy
matrix = np.array([[1,2,3], [4,5,6],[7,8,9]])

# Calculating inverse of a Matrix using NumPY's np.linalg.inv() function
print(f" Calculating Inverse of a Matrix using NumPY's np.linalg.inv() function:-\nA=\n{matrix}\n\nInverse of A=\n{np.linalg.inv(matrix)}\n")

 Calculating Inverse of a Matrix using NumPY's np.linalg.inv() function:-
A=
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Inverse of A=
[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]



## Other NumPy module for matrix operations :-


- **divide()** − divide elements of two matrices.

In [163]:
# Creating 2 2D matrix using Numpy
matrix_A = np.array([[1,2], [4,8]])
matrix_B = np.array([[1,2], [2,2]])

# Dividing elements of two matrices using NumPy's divide() function
print(f'{matrix_B}\n   /\n{matrix_A}\n   =\n{np.divide(matrix_B,matrix_A)}')

[[1 2]
 [2 2]]
   /
[[1 2]
 [4 8]]
   =
[[1.   1.  ]
 [0.5  0.25]]


- **sqrt()** − square root of each element of matrix.

In [169]:
# Creating a 2D matrix using Numpy
matrix = np.array([[1,4], [9,16]])

# Calculating square root of each element of matrix using NumPy's sqrt() function
print(f'Square root of each element of \n{matrix}\n=\n{np.sqrt(matrix)}')

Square root of each element of 
[[ 1  4]
 [ 9 16]]
=
[[1. 2.]
 [3. 4.]]


- **sum(x,axis)** − add to all the elements in matrix. Second argument is optional, it is used when we want to compute the column sum if axis is 0 and row sum if axis is 1.

In [177]:
# Creating a 2D matrix using Numpy
matrix = np.array([[1,2], [3,4]])

# Adding  all the elements in matrix. using NumPy's sum() function
print(f'Sum of all element of \n{matrix}\n   =\n   {np.sum(matrix)}')

Sum of all element of 
[[1 2]
 [3 4]]
   =
   10
